# Generated by Django 5.2.7 on 2025-10-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_completed',
            new_name='task_status',
        ),
    ]
